rugbystat/conf/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.urls import reverse_lazy
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView
from rest_framework.routers import DefaultRouter


from clippings.views import import_from_dropbox
from clippings.viewsets import (DocumentViewSet,
                                SourceViewSet,
                                SourceObjectViewSet)
from main import views
from matches.views import (import_seasons, import_table,
                           SeasonCreateView, SeasonDetailView, SeasonYearView,
                           MatchDetailView,
                           TournamentListView, TournamentDetailView,
                           TournamentAutocomplete, SeasonAutocomplete)
from teams.views import (import_teams,
                         PersonCreateView, PersonUpdateView,
                         TeamUpdateView, TeamSeasonView, TeamAllYearView,
                         TagAutocomplete, CityAutocomplete,
                         TeamAutocomplete, TeamSeasonAutocomplete,
                         PersonSeasonAutocomplete,
                         TeamBySeasonAutocomplete, PersonBySeasonAutocomplete)
from teams.viewsets import TeamViewSet, TeamSeasonViewSet, PersonViewSet, PersonSeasonViewSet
from matches.viewsets import MatchViewSet, SeasonViewSet
from users.viewsets import UserViewSet

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'teams', TeamViewSet)
router.register(r'teams-seasons', TeamSeasonViewSet)
router.register(r'persons', PersonViewSet)
router.register(r'personseasons', PersonSeasonViewSet)
router.register(r'teams/(?P<team_id>\d+)/documents', DocumentViewSet)
router.register(r'documents', DocumentViewSet)
router.register(r'sources', SourceViewSet)
router.register(r'issues', SourceObjectViewSet)
router.register(r'seasons', SeasonViewSet)
router.register(r'matches', MatchViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('allauth.urls')),
    url(r'^api/v1/', include(router.urls)),
    url(r'^api/v1/', include('authentication.urls')),
    #  url(r'^django-rq/', include('django_rq.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^import-teams/', import_teams),
    url(r'^import-seasons/', import_seasons, name='import_seasons'),
    url(r'^import-table/', import_table, name='import_table'),
    url(r'^dropbox-webhook/', import_from_dropbox),

    url(r'^autocomplete-tags/$', TagAutocomplete.as_view(),
        name='autocomplete-tags'),
    url(r'^autocomplete-cities/$', CityAutocomplete.as_view(),
        name='autocomplete-cities'),
    url(r'^autocomplete-tournaments/$', TournamentAutocomplete.as_view(),
        name='autocomplete-tournaments'),
    url(r'^autocomplete-seasons/$', SeasonAutocomplete.as_view(),
        name='autocomplete-seasons'),
    url(r'^autocomplete-teams/$', TeamAutocomplete.as_view(),
        name='autocomplete-teams'),
    url(r'^autocomplete-teamseasons/$', TeamSeasonAutocomplete.as_view(),
        name='autocomplete-teamseasons'),
    url(r'^autocomplete-personseasons/$', PersonSeasonAutocomplete.as_view(),
        name='autocomplete-personseasons'),
    url(r'^autocomplete-teambyseasons/$', TeamBySeasonAutocomplete.as_view(),
        name='autocomplete-teamseasons'),
    url(r'^autocomplete-personbyseasons/$', PersonBySeasonAutocomplete.as_view(),  # noqa
        name='autocomplete-personseasons'),

    url(r'^teams/$', views.teams_view, name='teams'),
    url(r'^teams/(?P<pk>\d+)/$',
        TeamUpdateView.as_view(), name='teams_detail'),
    url(r'^teams/(?P<pk>\d+)/(?P<year>\d{4})/all/',
        TeamAllYearView.as_view(), name='team_year_all'),
    url(r'^teams/(?P<team_pk>\d+)/(?P<year>\d{4})/(?P<pk>\d+)/',
        TeamSeasonView.as_view(), name='teamseason_detail'),
    url(r'^tournaments/$', TournamentListView.as_view(), name='tournaments'),
    url(r'^tournaments/(?P<pk>\d+)/$', TournamentDetailView.as_view(),
        name='tournament_detail'),
    url(r'^tournaments/(?P<tourn_pk>\d+)/(?P<lap>[\d\-]{4,7})/(?P<season_pk>\d+)/matches/(?P<pk>\d+)/',
        MatchDetailView.as_view(), name='match_detail'),
    url(r'^tournaments/(?P<tourn_pk>\d+)/(?P<lap>[\d\-]{4,7})/(?P<pk>\d+)/',
        SeasonDetailView.as_view(), name='season_detail'),
    url(r'^seasons/(?P<year>\d{4})/$', SeasonYearView.as_view(),
        name='seasons_year'),
    url(r'^seasons/new/$', SeasonCreateView.as_view(), name='seasons_new'),
    url(r'^persons/$', views.persons_view, name='persons'),
    url(r'^persons/(?P<pk>\d+)/', PersonUpdateView.as_view(),
        name='persons_detail'),
    url(r'^persons/new/', PersonCreateView.as_view(), name='persons_new'),

    url(r'^clippings/', views.clippings_view, name='clippings'),
    url(r'^contacts/', views.contacts_view, name='contacts'),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('tournaments'), permanent=False)),

    # the 'api-root' from django rest-frameworks default router
    # http://www.django-rest-framework.org/api-guide/routers/#defaultrouter
    url(r'^$', RedirectView.as_view(url=reverse_lazy('api-root'),
        permanent=False)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

rugbystat/teams/models.py
import datetime as dt

from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models, transaction
from django.db.models import Q
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _
from markdownx.models import MarkdownxField


class TagObject(models.Model):
    name = models.CharField(max_length=127, verbose_name=_('Базовое название'))
    story = MarkdownxField(verbose_name=_('История'), blank=True, )

    def __str__(self):
        return "Model: {0}".format(repr(self.target))

    @property
    def target(self):
        if getattr(self, 'team', None) is not None:
            return self.team
        if getattr(self, 'tournament', None) is not None:
            return self.tournament
        if getattr(self, 'season', None) is not None:
            return self.season
        if getattr(self, 'match', None) is not None:
            return self.match
        if getattr(self, 'person', None) is not None:
            return self.person
        return None

    @cached_property
    def documents(self):
        """
        >>> person.tagobject_ptr.document_set.all()
        <QuerySet [<Document: 1933>]>

        :return:
        :rtype:
        """
        return self.tagobject_ptr.document_set.all()


class City(models.Model):
    name = models.CharField(max_length=127, verbose_name=_('Базовое название'))
    short_name = models.CharField(
        max_length=4, verbose_name=_('Короткое название'), blank=True)

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name

    def get_short_name(self):
        return self.short_name or self.name


class Stadium(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name=_('Город'))
    name = models.CharField(max_length=127, verbose_name=_('Базовое название'))
    # TODO add historic names

    def __str__(self):
        return self.name


class Team(TagObject):
    CLUB = 'club'
    YOUTH = 'youth'
    NATION = 'nation'
    FOREIGN = 'foreign'
    TYPES = (
        (CLUB, CLUB),
        (YOUTH, YOUTH),
        (NATION, NATION),
        (FOREIGN, FOREIGN),
    )
    team_type = models.CharField(
        max_length=32, verbose_name=_('Короткое название'), choices=TYPES, default=CLUB,
    )
    short_name = models.CharField(
        max_length=32, verbose_name=_('Короткое название'), blank=True)
    city = models.ForeignKey(
        City, on_delete=models.CASCADE, verbose_name=_('Город'), related_name='teams')
    year = models.PositiveSmallIntegerField(
        verbose_name=_('Год создания'), blank=True, null=True,
        validators=(MinValueValidator(1900), MaxValueValidator(2100)),
    )
    disband_year = models.PositiveSmallIntegerField(
        verbose_name=_('Год распада'), blank=True, null=True,
        validators=(MinValueValidator(1900), MaxValueValidator(2100)),
    )
    year_prefix = models.CharField(
        max_length=64, verbose_name=_('Префикс к году образования'),
        blank=True, null=True,)
    disband_year_prefix = models.CharField(
        max_length=64, verbose_name=_('Префикс к году распада'),
        blank=True, null=True,)
    parent = models.ForeignKey(
        'self', on_delete=models.SET_NULL, verbose_name=_('Команда-родитель'),
        related_name='ancestors', blank=True, null=True)

    class Meta:
        ordering = ('year', )

    def __str__(self):
        team = self.short_name or self.name
        return "{} ({})".format(team, self.operational_years)

    def save(self, **kwargs):
        if not self.short_name:
            self.short_name = "{} {}".format(self.name,
                                             self.city.get_short_name())
        super(Team, self).save(**kwargs)

    @cached_property
    def operational_years(self):
        years = "{}{}".format(self.year_prefix or '',
                              self.year or '')
        if self.disband_year or self.disband_year_prefix:
            years += "-{}{}".format(self.disband_year_prefix or '',
                                    self.disband_year or '')
        return years

    def get_absolute_url(self):
        return reverse('teams_detail', kwargs={'pk': self.pk})

    def get_name_for(self, year, month=1, day=1):
        """Return name which team born in a given year."""
        default = self.short_name
        from_db = self.names.reverse().filter(
            from_day__lte=dt.date(year, month, day),
        ).filter(
            Q(to_day__gte=dt.date(year, month, day)) | Q(to_day__isnull=True)
        ).values_list('name', flat=True).first()
        return from_db or default


class TeamName(models.Model):
    """Representation of a separate name a team beared."""

    name = models.CharField(verbose_name=_('Базовое название'), max_length=127)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, verbose_name=_('Команда'), related_name='names')
    from_day = models.DateField(verbose_name=_('Дата начала'))
    to_day = models.DateField(verbose_name=_('Дата окончания'), blank=True, null=True)
    is_known = models.BooleanField(verbose_name=_('Подтверждено'), default=True)

    class Meta:
        ordering = ('team', 'from_day', )

    def __str__(self):
        years = '...'
        if self.is_known:
            if not self.to_day:
                years = "с {:%Y}".format(self.from_day)
            else:
                years = "{:%Y}-{:%Y}".format(self.from_day, self.to_day)
        return "{} ({})".format(self.name, years)


class TableRowFields(models.Model):
    place = models.CharField(
        verbose_name=_('Место'), max_length=2, blank=True,
    )
    played = models.PositiveSmallIntegerField(
        verbose_name=_('И'), null=True, blank=True,
        validators=(MaxValueValidator(100),),
    )
    wins = models.PositiveSmallIntegerField(
        verbose_name=_('В'), null=True, blank=True,
        validators=(MaxValueValidator(100),),
    )
    draws = models.PositiveSmallIntegerField(
        verbose_name=_('Н'), null=True, blank=True,
        validators=(MaxValueValidator(100),),
    )
    losses = models.PositiveSmallIntegerField(
        verbose_name=_('П'), null=True, blank=True,
        validators=(MaxValueValidator(100),),
    )
    points = models.PositiveSmallIntegerField(
        verbose_name=_('О'), null=True, blank=True,
        validators=(MaxValueValidator(200),),
    )
    score = models.CharField(
        verbose_name=_('Р/О'), max_length=10, blank=True
    )
    order = models.PositiveSmallIntegerField(
        verbose_name=_('Сортировка'), null=True, blank=True,
        validators=(MaxValueValidator(40),),
    )

    class Meta:
        abstract = True


class GroupSeason(TableRowFields):
    """Representation of each group in a tournament played"""

    name = models.CharField(verbose_name=_('Название команды в группе'),
                            max_length=127, blank=True)
    year = models.PositiveSmallIntegerField(
        verbose_name=_('Год'), blank=True, null=True,
        validators=(MinValueValidator(1900), MaxValueValidator(2100)),
    )
    # both `name` and `year` serves only for simpler repr and sql query
    team = models.ForeignKey(
        Team, on_delete=models.CASCADE, verbose_name=_('Команда'), related_name='groups',
    )
    group = models.ForeignKey(
        'matches.Group', on_delete=models.CASCADE, verbose_name=_('Группа'),
        related_name='standings'
    )
    story = models.TextField(verbose_name=_('История'), blank=True, )

    class Meta:
        ordering = ('order', '-year', 'team',)
        unique_together = (('team', 'group'),)

    def __str__(self):
        return "{}: {}".format(self.group, self.name)

    def save(self, **kwargs):
        if not self.year:
            self.year = self.group.date_end.year
        if not self.name:
            self.name = self.team.get_name_for(self.year)
        super(GroupSeason, self).save(**kwargs)

    def get_absolute_url(self):
        if self.team_id:
            team_in_m2m = self.group.teams.filter(team_id=self.team_id).first()
            if team_in_m2m:
                return team_in_m2m.get_absolute_url()

    def build(self):
        played, unknown_score = 0, 0
        wins, drws, loss = 0, 0, 0
        score_for, score_aga = 0, 0
        for match in self.group.matches():
            if self.team_id in (match.home_id, match.away_id):
                played += 1
                if match.is_unknown_outcome:
                    continue

                if match.is_team_win(self.team_id):
                    wins += 1
                if match.is_team_loss(self.team_id):
                    loss += 1
                if match.is_draw:
                    drws += 1
                
                if match.is_unknown_score:
                    unknown_score += 1
                else:
                    for_, aga_ = match.team_score(self.team_id)
                    score_for += for_
                    score_aga += aga_

        if wins + drws + loss != played:
            raise ValueError(f"{wins} + {drws} + {loss} != {played}")

        self.played = played
        self.wins = wins
        self.draws = drws
        self.losses = loss

        if not unknown_score:
            self.score = f"{score_for}-{score_aga}"
        return self


class TeamSeason(TableRowFields):
    """Representation of each tournament a team played"""

    name = models.CharField(
        verbose_name=_('Название команды в турнире'), max_length=127, blank=True
    )
    display_name = models.CharField(
        verbose_name=_('Полное наименование сезона'), max_length=127, blank=True,
    )
    year = models.PositiveSmallIntegerField(
        verbose_name=_('Год'), blank=True, null=True,
        validators=(MinValueValidator(1900), MaxValueValidator(2100)),
    )
    # both `name` and `year` serves only for simpler repr and sql query

rugbystat/templates/teams/person_detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}{{ block.super }} | {{ object.full_name }}{% endblock title %}

11
{% block css %}

{{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/modal.css' %}">

{% endblock css %}

{% block js %}

{{ block.super }}
  <script type="text/javascript" src="{% static 'js/persons.js' %}"></script>
  <script type="text/javascript">
    var personListUrl = "{% url 'person-list' %}";
  </script>

{% endblock js %}


{% block content %}

<div class="form-group">
  <label class="control-label" for="focusedInput">&nbsp;</label>
  <div class="input-group">
    <input type="text" class="form-control" id="person-input" />
    <span class="input-group-btn">
      <button class="btn btn-default" id="search-submit-btn" type="button">Искать</button>
    </span>
  </div>
</div>

<span id="indicator" style="display:none;"><img src="http://upload.wikimedia.org/wikipedia/commons/d/de/Ajax-loader.gif"/></span>
<div id="results"></div>

<h2>{{ object.full_name }}</h2>

{{ form }}

<div class="dossier">
  {% if "-" in object.living_years %}
    Годы жизни: {{ object.living_years }}
  {% else %}
    Дата рождения: {{ object.living_years }}
  {% endif %}
</div>
<div class="story">{{ object.story | safe }}</div>

{% if object.seasons.all %}
<h4>Сезоны</h4>
<table class="table table-striped table-hover" id="person-seasons">
<thead>
  <tr>
    <th>Год</th>
    <th>Амплуа</th>
    <th>Турнир</th>
    <th>Команда</th>
    <th>Комментарии</th>
  </tr>
</thead>
<tbody>
{% for season in object.seasons.all %}
  <tr class="document-row">
    <td> {{ season.year }} </td>
    <td> {{ season.role_verbose|default:"" }} </td>
    <td> 
    {% if season.tournament %}
      <a class="link" 
         href="#">
         {{ season.tournament }}
      </a>
    {% else %}
      -
    {% endif %}
    </td>
    <td>
    {% if season.team %}
      {{ season.team }}
    {% else %}
      -
    {% endif %}
    </td>
    <td> {{ season.story | markdown }} </td>
  </tr>
{% endfor %}
</tbody></table>
{% endif %}

{% if object.documents %}
<h4>Документы</h4>
<table class="table table-striped table-hover" id="documents-table">
  <thead>
    <tr>
      <th>Заголовок</th>
      <th>Описание</th>
      <th>Месяц/Год</th>
      <th>Ссылка</th>
    </tr>
  </thead>
  <tbody>
    
  {% for doc in object.documents %}
  <tr class="document-row">
    <td> {{ doc.title }} </td>
    <td> {{ doc.description }} </td>
    <td> {{ doc.date }} </td>
    <td> {% if doc.is_image %}
      <a class="dropbox-link" 
         href="{{ doc.dropbox_path }}">
         <img src="{{ doc.dropbox_thumb }}"/>
      </a>
    {% else %}
      <a class="dropbox-link" 
         href="{{ doc.dropbox_path }}">
         Нет превью
      </a>
    {% endif %}
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>

{% endif %}

{% include '_modal.html' %}

{% endblock content %}

rugbystat/templates/teams/team_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% load markdownx %}

{% block title %}{{ block.super }} | {{object.name}} {{ object.city.name }}{% endblock title %}

{% block stylesheets %}

{{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/modal.css' %}">
  <!-- Include Bootstrap Datepicker -->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" />
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />
{% endblock stylesheets %}

{% block js %}

{{ block.super }}
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>
  <script type="text/javascript" src="{% static 'js/teams.js' %}"></script>
  <script type="text/javascript">
    var teamListUrl = "{% url 'team-list' %}",
        teamSeasonListUrl = "{% url 'teamseason-list' %}",
        teamUpdate = "{% url 'teams_detail' pk=object.pk %}",
        team = {{ object.pk }};
  </script>
{% endblock js %}

{% block content %}
<div class="form-group">
  <label class="control-label" for="focusedInput">&nbsp;</label>
  <div class="input-group">
    <input type="search" class="form-control" id="team-input" />
    <span class="input-group-btn">
      <button class="btn btn-default" id="search-submit-btn" type="button">Искать</button>
    </span>
  </div>
</div>

<span id="indicator" style="display:none;"><img src="http://upload.wikimedia.org/wikipedia/commons/d/de/Ajax-loader.gif"/></span>
<div id="results"></div>

<div class="pull-right">
  {% if user.is_authenticated %}
  <button class="btn btn-default" id="showTeamForm" type="button">Редактировать</button>
  {% endif %}
</div>

<h2 id="name" class="editable">{{ object.name }} {{ object.city.name }} ({{ object.operational_years }})</h2>

<div id="formErrors">
{% if form.errors %}
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="fieldError">
        {{ field.errors }}
    </div>
    {% endfor %}
{% endif %}
</div>

<form role="form" id="teamForm"
      method="POST" action="{% url 'teams_detail' pk=object.pk %}"
      style="display: none;">
{% csrf_token %}
<div id="dossierForm" class="form-inputs">
  <div class="form-inline row">
    <div class="col-sm-3">
      {% render_field form.year_prefix class+="form-control" %}
      <span class="help-block">{{ form.year_prefix.label }}</span>
    </div>
    <div class="col-sm-3">
      {% render_field form.year class+="form-control" %}
      <span class="help-block">{{ form.year.label }}</span>
    </div>
    <div class="col-sm-3">
      {% render_field form.disband_year_prefix class+="form-control" %}
      <span class="help-block">{{ form.disband_year_prefix.label }}</span>
    </div>
    <div class="col-sm-3">
      {% render_field form.disband_year class+="form-control" %}
      <span class="help-block">{{ form.disband_year.label }}</span>
    </div>
  </div>
</div>
<div id="storyForm" class="form-inputs">
  <div class="form-group">
    {% render_field form.story class+="form-control" rows="5" %}
    <span class="help-block">{{ form.story.label }}</span>
  </div>
</div>
<div id="submitForm">
  <div class="form-group">
    <button class="btn btn-default" id="submitTeamForm" type="submit">Сохранить</button>
    <button class="btn btn-secondary" id="cancelTeamForm" type="submit">Отмена</button>
  </div>
</div>
</form>

{{ form.media }}

<div id="dossier" class="editable">
  <b>Годы:</b> {{ object.operational_years }}
</div>

{% if object.names.all %}
<b>Названия:</b>
<ul>
{% for name in object.names.all %}
<li>{{ name }}</li>
{% endfor %}
</ul>
{% endif %}

<div id="story" class="editable">
  <b>История:</b>
  <div>{{ object.story | markdown }}</div>
</div>

{% if user.is_authenticated %}
<form role="form" id="addSeason" class="addForm" style="display: none;">
  {% csrf_token %}
  
  <div id="formErrors">
    {% if form.errors %}
        {{ form.non_field_errors }}
        {% for field in form %}
        <div class="fieldError">
            {{ field.errors }}
        </div>
        {% endfor %}
    {% endif %}
    </div>

  <h3>Добавить сезон</h3>
  <div class="form-inputs">
    <input type="hidden" 
           name="team" 
           id="id_team" 
           value="{{ season_form.team.value }}">
  
    <div>
      <div class="col-sm-3 text-center">
        <span class="help-block">{{ season_form.season.label }}</span>
      </div>
      <div class="col-sm-2 text-center">
        <span class="help-block">{{ season_form.name.label }}</span>
      </div>
      <div class="col-sm-1 text-center has-error">
        <span class="help-block">{{ season_form.place.label }}</span>
      </div>
      <div class="col-sm-1 text-center has-error">
        <span class="help-block">{{ season_form.played.label }}</span>
      </div>
      <div class="col-sm-1 text-center has-error">
        <span class="help-block">{{ season_form.wins.label }}</span>
      </div>
      <div class="col-sm-1 text-center">
        <span class="help-block">{{ season_form.draws.label }}</span>
      </div>
      <div class="col-sm-1 text-center">
        <span class="help-block">{{ season_form.losses.label }}</span>
      </div>
      <div class="col-sm-1 text-center">
        <span class="help-block">{{ season_form.points.label }}</span>
      </div>
      <div class="col-sm-1 text-center">
        <span class="help-block">{{ season_form.score.label }}</span>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-3">
        {% render_field season_form.season class+="form-control" %}
      </div>
      <div class="col-sm-2">
        {% render_field season_form.name class+="form-control" %}
      </div>
      <div class="col-sm-1">
        {% render_field season_form.place class+="form-control" %}
      </div>
      <div class="col-sm-1">
        {% render_field season_form.played class+="form-control" %}
      </div>
      <div class="col-sm-1">
        {% render_field season_form.wins class+="form-control" %}
      </div>
      <div class="col-sm-1">
        {% render_field season_form.draws class+="form-control" %}
      </div>
      <div class="col-sm-1">
        {% render_field season_form.losses class+="form-control" %}
      </div>
      <div class="col-sm-1">
        {% render_field season_form.points class+="form-control" %}
      </div>
      <div class="col-sm-1">
        {% render_field season_form.score class+="form-control" %}
      </div>
    </div>
  
    <div class="form-group row">
      <div class="col-sm-12">
        {% render_field season_form.story class+="form-control" rows="2" %}
        <span class="help-block">Произвольная информация о сезоне</span>
      </div>
    </div>
  </div>
  
  {{ season_form.media }}
  
    <div class="pull-right">
      <button class="btn btn-default submitForm" 
              id="submitSeasonForm" 
              type="button">Сохранить</button>
      <button class="btn btn-secondary cancelForm" 
              id="cancelSeasonForm" 
              type="button">Отмена</button>
    </div>
  </form>
  
    <div class="pull-right">
      <button class="btn btn-default showForm" 
              id="showTeamSeasonForm" 
              type="button">Добавить сезон</button>
    </div>
  
{% endif %}

{% if seasons %}
<h3>Сезоны</h3>
<table class="table table-striped table-hover" id="person-seasons">
<thead>
  <tr>
    <th>Турнир</th>
    <th>И</th>
    <th>В</th>
    <th>Н</th>
    <th>П</th>
    <th>Р/О</th>
    <th>О</th>
    <th>-</th>
    <th>М</th>
  </tr>
</thead>
<tbody>
{% for season in seasons %}
  <tr class="document-row">
    <td> 
      <a class="link" href="{{ season.get_absolute_url }}">
         {{ season.season }}
      </a>
    </td>

    {% include 'matches/table_row.html' with team=season %}

    <td class="tbl-position"> 
      {{ season.get_position }}
    </td>
  </tr>
{% endfor %}
</tbody></table>
{% endif %}

{% if documents %}
<h3>Документы</h3>
  {% include '_documents.html' with queryset=documents %}
{% endif %}

{% include '_modal.html' with modal_id="moderationModal" %}

{% endblock content %}

rugbystat/templates/teams/team_year.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}{{ block.super }} | {{ team_name }} | Все матчи {{ year }}{% endblock title %}

{% block content %}

<h2 id="name"><a href="{{ team.get_absolute_url }}">{{ team_name }}</a></h2>

<table class="table table-striped table-hover" id="documents-table">
    <thead>
      <tr>
        <th>Дата</th>
        <th>Матч</th>
        <th>Турнир</th>
      </tr>
    </thead>
    <tbody>
  
    {% for match in matches %}
    <tr>
      <td>{{ match.get_date }}</td>
      <td><a href="{{ match.get_absolute_url }}">{{ match.display_name }}</a></td>
      <td><a href="{{ match.tourn_season.get_absolute_url }}">{{ match.tourn_season }}</a></td>
    </tr>
    {% endfor %}

    </tbody>
</table>
{% endblock content %}