rugbystat/conf/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.urls import reverse_lazy
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView
from rest_framework.routers import DefaultRouter


from clippings.views import import_from_dropbox
from clippings.viewsets import (DocumentViewSet,
                                SourceViewSet,
                                SourceObjectViewSet)
from main import views
from matches.views import (import_seasons, import_table,
                           SeasonCreateView, SeasonDetailView, SeasonYearView,
                           MatchDetailView,
                           TournamentListView, TournamentDetailView,
                           TournamentAutocomplete, SeasonAutocomplete)
from teams.views import (import_teams,
                         PersonCreateView, PersonUpdateView,
                         TeamUpdateView, TeamSeasonView, TeamAllYearView,
                         TagAutocomplete, CityAutocomplete,
                         TeamAutocomplete, TeamSeasonAutocomplete,
                         PersonSeasonAutocomplete,
                         TeamBySeasonAutocomplete, PersonBySeasonAutocomplete)
from teams.viewsets import TeamViewSet, TeamSeasonViewSet, PersonViewSet, PersonSeasonViewSet
from matches.viewsets import MatchViewSet, SeasonViewSet
from users.viewsets import UserViewSet

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'teams', TeamViewSet)
router.register(r'teams-seasons', TeamSeasonViewSet)
router.register(r'persons', PersonViewSet)
router.register(r'personseasons', PersonSeasonViewSet)
router.register(r'teams/(?P<team_id>\d+)/documents', DocumentViewSet)
router.register(r'documents', DocumentViewSet)
router.register(r'sources', SourceViewSet)
router.register(r'issues', SourceObjectViewSet)
router.register(r'seasons', SeasonViewSet)
router.register(r'matches', MatchViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('allauth.urls')),
    url(r'^api/v1/', include(router.urls)),
    url(r'^api/v1/', include('authentication.urls')),
    #  url(r'^django-rq/', include('django_rq.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^import-teams/', import_teams),
    url(r'^import-seasons/', import_seasons, name='import_seasons'),
    url(r'^import-table/', import_table, name='import_table'),
    url(r'^dropbox-webhook/', import_from_dropbox),

    url(r'^autocomplete-tags/$', TagAutocomplete.as_view(),
        name='autocomplete-tags'),
    url(r'^autocomplete-cities/$', CityAutocomplete.as_view(),
        name='autocomplete-cities'),
    url(r'^autocomplete-tournaments/$', TournamentAutocomplete.as_view(),
        name='autocomplete-tournaments'),
    url(r'^autocomplete-seasons/$', SeasonAutocomplete.as_view(),
        name='autocomplete-seasons'),
    url(r'^autocomplete-teams/$', TeamAutocomplete.as_view(),
        name='autocomplete-teams'),
    url(r'^autocomplete-teamseasons/$', TeamSeasonAutocomplete.as_view(),
        name='autocomplete-teamseasons'),
    url(r'^autocomplete-personseasons/$', PersonSeasonAutocomplete.as_view(),
        name='autocomplete-personseasons'),
    url(r'^autocomplete-teambyseasons/$', TeamBySeasonAutocomplete.as_view(),
        name='autocomplete-teamseasons'),
    url(r'^autocomplete-personbyseasons/$', PersonBySeasonAutocomplete.as_view(),  # noqa
        name='autocomplete-personseasons'),

    url(r'^teams/$', views.teams_view, name='teams'),
    url(r'^teams/(?P<pk>\d+)/$',
        TeamUpdateView.as_view(), name='teams_detail'),
    url(r'^teams/(?P<pk>\d+)/(?P<year>\d{4})/all/',
        TeamAllYearView.as_view(), name='team_year_all'),
    url(r'^teams/(?P<team_pk>\d+)/(?P<year>\d{4})/(?P<pk>\d+)/',
        TeamSeasonView.as_view(), name='teamseason_detail'),
    url(r'^tournaments/$', TournamentListView.as_view(), name='tournaments'),
    url(r'^tournaments/(?P<pk>\d+)/$', TournamentDetailView.as_view(),
        name='tournament_detail'),
    url(r'^tournaments/(?P<tourn_pk>\d+)/(?P<lap>[\d\-]{4,7})/(?P<season_pk>\d+)/matches/(?P<pk>\d+)/',
        MatchDetailView.as_view(), name='match_detail'),
    url(r'^tournaments/(?P<tourn_pk>\d+)/(?P<lap>[\d\-]{4,7})/(?P<pk>\d+)/',
        SeasonDetailView.as_view(), name='season_detail'),
    url(r'^seasons/(?P<year>\d{4})/$', SeasonYearView.as_view(),
        name='seasons_year'),
    url(r'^seasons/new/$', SeasonCreateView.as_view(), name='seasons_new'),
    url(r'^persons/$', views.persons_view, name='persons'),
    url(r'^persons/(?P<pk>\d+)/', PersonUpdateView.as_view(),
        name='persons_detail'),
    url(r'^persons/new/', PersonCreateView.as_view(), name='persons_new'),

    url(r'^clippings/', views.clippings_view, name='clippings'),
    url(r'^contacts/', views.contacts_view, name='contacts'),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('tournaments'), permanent=False)),

    # the 'api-root' from django rest-frameworks default router
    # http://www.django-rest-framework.org/api-guide/routers/#defaultrouter
    url(r'^$', RedirectView.as_view(url=reverse_lazy('api-root'),
        permanent=False)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

rugbystat/matches/models.py
import logging
import typing as t

from babel.dates import format_date
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from teams.models import TagObject, Team, TeamSeason, GroupSeason
# from teams.models import Stadium, Person

logger = logging.getLogger("rugbystat")


class Tournament(TagObject):
    """Representation of each tournament that might exist:

    - Чемпионат СССР
    - Чемпионат СССР. Первая лига
    - Кубок СССР
    - Первенство Украины
    ...
    """

    level = models.PositiveSmallIntegerField(
        verbose_name=_("Уровень"), default=0, blank=False, null=False
    )

    class Meta:
        ordering = ("level",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("tournament_detail", kwargs={"pk": self.pk})

    def get_name_with_seasons(self):
        """Iterate on all related seasons to find first and last.

        E.g. Чемпионат СССР (1936-1991)"""
        all_seasons = list(self.seasons.all())
        try:
            first = all_seasons[0]
            last = all_seasons[-1]

            years = first.date_start.year
            if last.date_end.year != years:
                years = f'{years}-{last.date_end.year}'
        except IndexError:
            years = "-"

        return f'{self.name} ({years})'


class Season(TagObject):
    """Each specific drawing of a Tournament"""

    tourn = models.ForeignKey(
        Tournament, on_delete=models.CASCADE, verbose_name=_("Турнир"), related_name="seasons"
    )
    date_start = models.DateField(verbose_name=_("Дата начала"))
    date_end = models.DateField(verbose_name=_("Дата окончания"))

    participants = models.PositiveSmallIntegerField(
        verbose_name=_('Число участников'), blank=True, null=True,
    )

    class Meta:
        ordering = ("tourn", "date_start")

    def __str__(self):
        return self.name

    def save(self, **kwargs):
        self.full_clean()
        if not self.pk:
            self.name = self._get_name()
        super(Season, self).save(**kwargs)

    def full_clean(self, **kwargs):
        super(Season, self).full_clean(**kwargs)
        name = self._get_name()
        if Season.objects.filter(name=name).exclude(pk=self.pk).exists():
            msg = "Such season already exists: {}"
            raise ValidationError(msg.format(name))

    def get_absolute_url(self):
        lap = self._get_lap().replace("/", "-")
        return reverse(
            "season_detail",
            kwargs={"tourn_pk": self.tourn_id, "lap": lap, "pk": self.pk},
        )

    def get_table(self):
        """
        Return list of TeamSeason-s sorted by place
        """
        return self.standings.order_by("order")

    def _get_lap(self):
        """
        Return year part for season: '1977' for Чемпионат СССР 1978
        '1977/78' for Кубок СССР 1977/78
        """
        if self.date_start.year == self.date_end.year:
            lap = str(self.date_start.year)
        else:
            lap = "{}/{}".format(self.date_start.year, str(self.date_end.year)[-2:])
        return lap

    def _get_name(self):
        """
        Generate name like Чемпионат СССР 1978 or Кубок СССР 1977/78
        """
        return "{} {}".format(self.tourn, self._get_lap())

    def change_team(self, old_pk, new_pk):
        """Change team_id for all TeamSeason, GroupSeason, and matches."""
        self.standings.filter(team_id=old_pk).update(team_id=new_pk)
        GroupSeason.objects.filter(group_id__in=self.groups.values_list('pk', flat=True), team_id=old_pk).update(team_id=new_pk)
        self.matches.filter(home_id=old_pk).update(home_id=new_pk)
        self.matches.filter(away_id=old_pk).update(away_id=new_pk)


class Group(models.Model):
    """Stage of a Season: preliminary round, group A/gmroup B, etc."""

    ROUND = 'round-robin'
    KNOCKOUT = 'knockout'
    MISC = 'misc'
    TYPES = (
        (ROUND, ROUND),
        (KNOCKOUT, KNOCKOUT),
        (MISC, MISC)
    )

    name = models.CharField(verbose_name=_("Название"), max_length=127, blank=True)
    season = models.ForeignKey(
        Season, on_delete=models.CASCADE, verbose_name=_("Розыгрыш"), related_name="groups",
    )
    round_type = models.CharField(
        verbose_name=_("Тип игр"), max_length=127, choices=TYPES, default=ROUND,
    )
    date_start = models.DateField(verbose_name=_("Дата начала"))
    date_end = models.DateField(verbose_name=_("Дата окончания"))
    city = models.ForeignKey(
        "teams.City", on_delete=models.CASCADE, 
        verbose_name=_("Город"),
        related_name="groups",
        blank=True,
        null=True,
    )
    comment = models.TextField(verbose_name=_("Комментарий"), blank=True)
    teams = models.ManyToManyField(
        "teams.TeamSeason", related_name="groups", blank=True
    )

    class Meta:
        ordering = ("season", "date_end")

    def __str__(self):
        return "{0.date_start.year} {0.name}".format(self)

    def get_table(self):
        """
        Return list of GroupSeason-s sorted by place
        """
        return self.standings.order_by("order")

    @property
    def is_round_robin(self):
        return self.round_type == self.ROUND

    def matches(self):
        """Return all matches of the season which belong to the group."""
        teams = self.teams.values_list('team', flat=True)
        qs = self.season.matches.filter(home__in=teams, away__in=teams)
        qs = qs.exclude(date__lt=self.date_start)
        qs = qs.exclude(date__gt=self.date_end)
        return qs.order_by('date', 'pk')

    def fill_blanks(self):
        for gs in self.standings.all():
            try:
                gs.build().save()
            except ValueError as exc:
                logger.warning(f"{gs} matches: {exc}")


class MatchQuerySet(models.QuerySet):
    def for_team(self, team_pk):
        return self.filter(models.Q(home_id=team_pk) | models.Q(away_id=team_pk))


class Match(TagObject):

    _delimiter = '—'

    date = models.DateField(verbose_name="Дата матча", blank=True, null=True)
    date_unknown = models.CharField(
        verbose_name="Дата, если неизвестна",
        max_length=64, blank=True, null=True,
    )
    display_name = models.CharField(verbose_name="Отображение", max_length=255, blank=True)
    tourn_season = models.ForeignKey(
        Season, on_delete=models.SET_NULL,
        verbose_name=_("Турнир"), related_name="matches", blank=True, null=True
    )
    home = models.ForeignKey(
        Team, on_delete=models.CASCADE,
        verbose_name=_("Хозяева"), related_name="home_matches"
    )
    away = models.ForeignKey(Team, on_delete=models.CASCADE, verbose_name=_("Гости"), related_name="away_matches")
    home_score = models.PositiveSmallIntegerField(
        verbose_name=_("Счёт хозяев"), blank=True, null=True
    )
    away_score = models.PositiveSmallIntegerField(
        verbose_name=_("Счёт гостей"), blank=True, null=True
    )
    home_halfscore = models.PositiveSmallIntegerField(
        verbose_name=_("1 тайм хозяев"), blank=True, null=True
    )
    away_halfscore = models.PositiveSmallIntegerField(
        verbose_name=_("1 тайм гостей"), blank=True, null=True
    )

    # в случае потасовки на поле возможно поражение ОБЕИМ командам
    technical = models.BooleanField(verbose_name=_("Технический результат"), default=False)
    tech_home_loss = models.BooleanField(verbose_name=_("Поражение хозяевам"), default=False)
    tech_away_loss = models.BooleanField(verbose_name=_("Поражение гостям"), default=False)

    objects = MatchQuerySet.as_manager()

    def __str__(self):
        return self.name

    def save(self, **kwargs):
        if not self.display_name:
            self.update_match_name()
        super(Match, self).save(**kwargs)

    @property
    def is_unknown_outcome(self):
        return "??:??" in self.name

    @property
    def is_only_outcome(self):
        return any([self.tech_away_loss, self.tech_home_loss])

    @property
    def is_unknown_score(self):
        if self.is_unknown_outcome:
            return True

        for unkn in ("в:п", "п:в", "н:н"):
            if unkn in self.name:
                return True
        return False

    @property
    def is_home_win(self):
        if self.is_only_outcome:
            return self.tech_away_loss
        if not self.is_unknown_outcome:
            return self.home_score > self.away_score

    @property
    def is_away_win(self):
        if self.is_only_outcome:
            return self.tech_home_loss
        if not self.is_unknown_outcome:
            return self.home_score < self.away_score

    @property
    def is_draw(self):
        if not self.is_unknown_outcome:
            return not self.is_only_outcome and self.home_score == self.away_score

    def is_team_win(self, team_id):
        if team_id == self.home_id:
            return self.is_home_win
        if team_id == self.away_id:
            return self.is_away_win

    def is_team_loss(self, team_id):
        if team_id == self.home_id:
            return self.is_away_win
        if team_id == self.away_id:
            return self.is_home_win

    def team_score(self, team_id):
        if team_id == self.home_id:
            return self.home_score, self.away_score
        if team_id == self.away_id:
            return self.away_score, self.home_score

    def set_tech_score(self):
        if self.home_score == "-":
            self.technical = True
            self.home_score = None
            self.tech_home_loss = True
        if self.home_score == "+":
            self.technical = True
            self.home_score = None
            self.tech_away_loss = True
        if self.away_score == "-":
            self.technical = True
            self.away_score = None
            self.tech_away_loss = True
        if self.away_score == "+":
            self.technical = True

rugbystat/templates/matches/match_detail.html
{% extends "base.html" %}

{% load staticfiles %}
{% load widget_tweaks %}
{% load markdownx %}

{% block title %}{{ block.super }} | {{ object.name }}{% endblock title %}

{% block stylesheets %}
{{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/modal.css' %}">
  <!-- Include Bootstrap Datepicker -->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" />
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />
{% endblock stylesheets %}

{% block js %}
{{ block.super }}
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/locales/bootstrap-datepicker.ru.js"></script>
  <script type="text/javascript" src="{% static 'js/matches.js' %}"></script>
  <script type="text/javascript">
    var matchListUrl = "{% url 'match-list' %}",
        season = {{ object.pk }};
  </script>

{% endblock js %}

{% block content %}

<h3 id="name"><a href="{{ object.tourn_season.get_absolute_url }}">{{ object.tourn_season }}</a></h3>

<div class="date">
  {{ object.get_date }}
</div>
<div class="main-line">
  {{ object.get_display_with_links | safe }}
</div>

<article>{{ object.story | markdown }}</article>

{% if documents %}
<h3>Документы</h3>
  {% include '_documents.html' with queryset=documents %}
{% endif %}

{% endblock content %}

rugbystat/templates/matches/match_list.html
<ul>
{% for match in matches %}
  <li>{{ match.get_date }} <a href="{{ match.get_absolute_url }}">{{ match.display_name }}</a></li>
{% endfor %}
</ul>

rugbystat/templates/matches/season_archive_year.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}{{ block.super }} || Турниры {{ year|date:"Y" }} года{% endblock title %}

{% block content %}

<h2 id="name">{{ year|date:"Y" }}</h2>

<ul>
  {% for season in object_list %}
    <li> <a class="link" 
            href="{{ season.get_absolute_url }}">
            {{ season }}
         </a>
    </li>
  {% endfor %}
</ul>

<div>
    <ul class="pagination">
      {% if previous_year %}
        <li>
          <a href="{% url 'seasons_year' previous_year|date:"Y" %}">
            ❮ {{ previous_year|date:"Y" }}</a>
        </li>
      {% endif %}
      {% if next_year %}
        <li>
          <a href="{% url 'seasons_year' next_year|date:"Y" %}">
            {{ next_year|date:"Y" }} ❯</a>
        </li>
      {% endif %}
    </ul>
</div>

{% endblock content %}

rugbystat/templates/matches/season_detail.html
{% extends "base.html" %}

{% load staticfiles %}
{% load widget_tweaks %}
{% load markdownx %}

{% block title %}{{ block.super }} | {{ object.name }}{% endblock title %}

{% block stylesheets %}
{{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/modal.css' %}">
  <!-- Include Bootstrap Datepicker -->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" />
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />
{% endblock stylesheets %}

{% block js %}
{{ block.super }}
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/locales/bootstrap-datepicker.ru.js"></script>
  <script type="text/javascript" src="{% static 'js/matches.js' %}"></script>
  <script type="text/javascript">
    var matchListUrl = "{% url 'match-list' %}",
        season = {{ object.pk }};
  </script>

{% endblock js %}

{% block content %}

<div class="pull-right">
  <h4 id="all"><a href="{% url 'seasons_year' season.date_end.year %}">Все матчи сезона {{ season.date_end.year }}</a></h4>
</div>

<h2 id="name"><a href="{{ object.tourn.get_absolute_url }}">{{ object.name }}</a></h2>

<article>{{ object.story | markdown }}</article>

{% if user.is_authenticated %}
<form role="form" id="parseTable" class="addForm"
      method="POST" action="{% url 'import_table' %}">
  {% csrf_token %}
<div class="form-inputs">
  <div class="form-group row">
    <input type="hidden" 
      name="season" 
      id="id_season" 
      value="{{ object.pk }}">

    <div class="col-sm-12">
      {% render_field import_form.raw class+="form-control" %}
    </div>
  </div>
  <div class="pull-right">
    <input class="btn btn-default submitForm" 
            id="submitImportForm" 
            type="submit"/>
  </div>
</div>
</form>
{% endif %}

{% for group in object.groups.all %}

{% include 'matches/season_table.html' with object=group %}
{% empty %}
{% include 'matches/match_list.html' with matches=object.matches.all %}
{% endfor %}

{% if not user.is_anonymous %}
<form role="form" id="addMatch" class="addForm" style="display: none;">
{% csrf_token %}

<div id="formErrors">
  {% if match_form.errors %}
    {{ match_form.non_field_errors }}
    {% for field in match_form %}
      <div class="fieldError">
          {{ field.errors }}
      </div>
    {% endfor %}
  {% endif %}
</div>
  
<h3>Добавить матч</h3>
<div class="form-inputs">
  <input type="hidden" 
         name="tourn_season" 
         id="id_tourn_season" 
         value="{{ match_form.tourn_season.value }}">

  <div class="row">
    <div class="col-sm-2 text-center">
      <span class="help-block">{{ match_form.date.label }}</span>
    </div>
    <div class="col-sm-3 text-center has-error">
      <span class="help-block">{{ match_form.home.label }}</span>
    </div>
    <div class="col-sm-3 text-center has-error">
      <span class="help-block">{{ match_form.away.label }}</span>
    </div>
    <div class="col-sm-2 text-center">
      <span class="help-block">Счет</span>
    </div>
    <div class="col-sm-2 text-center">
      <span class="help-block">Счет 1 тайма</span>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-2">
      {% render_field match_form.date class+="form-control" %}
    </div>
    <div class="col-sm-3">
      {% render_field match_form.home %}
    </div>
    <div class="col-sm-3">
      {% render_field match_form.away class+="form-control" %}
    </div>
    <div class="col-sm-1">
      {% render_field match_form.home_score class+="form-control" %}
    </div>
    <div class="col-sm-1">
      {% render_field match_form.away_score class+="form-control" %}
    </div>
    <div class="col-sm-1">
      {% render_field match_form.home_halfscore class+="form-control" %}
    </div>
    <div class="col-sm-1">
      {% render_field match_form.away_halfscore class+="form-control" %}
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-12">
      {% render_field match_form.story class+="form-control" rows="2" %}
      <span class="help-block">Произвольная информация о матче</span>
    </div>
  </div>
</div>

{{ match_form.media }}

  <div class="pull-right">
    <button class="btn btn-default submitForm" 
            id="submitMatchForm" 
            type="button">Сохранить</button>
    <button class="btn btn-secondary cancelForm" 
            id="cancelMatchForm" 
            type="button">Отмена</button>
  </div>
</form>

  <div class="pull-right">
    <button class="btn btn-default showForm" 
            id="showMatchForm" 
            type="button">Добавить</button>
  </div>
{% endif %}

{% include '_modal.html' with modal_id="moderationModal" %}

{% if documents %}
<h3>Документы</h3>
  {% include '_documents.html' with queryset=documents %}
{% endif %}

<div>
  <ul class="pagination">
    {% if prev %}
      <li>
        <a href="{{ prev.get_absolute_url }}">
          ❮ {{ prev }}</a>
      </li>
    {% endif %}
    {% if next %}
      <li>
        <a href="{{ next.get_absolute_url }}">
          {{ next }} ❯</a>
      </li>
    {% endif %}
  </ul>
</div>

{% endblock content %}

rugbystat/templates/matches/season_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% load markdownx %}

{% block stylesheets %}

{{ block.super }}
  <!-- Include Bootstrap Datepicker -->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" />
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />
{% endblock stylesheets %}

{% block js %}

{{ block.super }}

  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/locales/bootstrap-datepicker.ru.js"></script>
  <script type="text/javascript" src="{% static 'js/import.js' %}"></script>

{% endblock js %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div id="formErrors">
{% if form.errors %}
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="fieldError">
        {{ field.errors }}
    </div>
    {% endfor %}
{% endif %}
</div>

<form role="form" id="seasonForm"
      method="POST" action="{% url 'seasons_new' %}">
{% csrf_token %}
<div id="seasonForm" class="form-inputs">
  <div class="form-inline row">
    <div class="col-sm-3">
      {% render_field form.name class+="form-control" %}
      <span class="help-block">{{ form.name.label }}</span>
    </div>
    <div class="col-sm-3">
      <div class="input-group input-append date">
        {% render_field form.date_start class+="form-control" %}
        <span class="input-group-addon add-on"><span class="glyphicon glyphicon-calendar"></span></span>
      </div>
      <span class="help-block">{{ form.date_start.label }}</span>
    </div>
    <div class="col-sm-3">
      <div class="input-group input-append date">
        {% render_field form.date_end class+="form-control" %}
        <span class="input-group-addon add-on"><span class="glyphicon glyphicon-calendar"></span></span>
      </div>
      <span class="help-block">{{ form.date_end.label }}</span>
    </div>
    <div class="col-sm-3">
      {% render_field form.tourn class+="form-control" %}
      <span class="help-block">{{ form.tourn.label }}</span>
    </div>
  </div>
</div>

<div id="storyForm" class="form-inputs">
  <div class="form-group">
    {% render_field form.story class+="form-control" rows="5" %}
    <span class="help-block">{{ form.story.label }}</span>
  </div>
</div>
<div id="submitForm">
  <div class="form-group">
    <button class="btn btn-default" id="submitSeasonForm" type="submit">Сохранить</button>
    <button class="btn btn-secondary" id="cancelSeasonForm" type="submit">Отмена</button>
  </div>
</div>
</form>

{{ form.media }}

{% endblock content %}

rugbystat/templates/matches/table_row.html
{% load table %}

<td>{{ team.played|table }}</td>
<td>{{ team.wins|table }}</td>
<td>{{ team.draws|table }}</td>
<td>{{ team.losses|table }}</td>
<td>{{ team.score|table }}</td>
<td>{{ team.points|table }}</td>
<td class="tbl-story">{{ team.story|table }}</td>

rugbystat/templates/matches/tournament_detail.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}

<h2 id="name">{{ object.name }}</h2>

<article>{{ object.story }}</article>

<ul>
  {% for season in object.seasons.all %}
    <li>
      <a class="link"
         href="{{ season.get_absolute_url }}">
           {{ season }}
      </a>
    </li>
  {% endfor %}
</ul>

{% endblock content %}