rugbystat/conf/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.urls import reverse_lazy
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView
from rest_framework.routers import DefaultRouter


from clippings.views import import_from_dropbox
from clippings.viewsets import (DocumentViewSet,
                                SourceViewSet,
                                SourceObjectViewSet)
from main import views
from matches.views import (import_seasons, import_table,
                           SeasonCreateView, SeasonDetailView, SeasonYearView,
                           MatchDetailView,
                           TournamentListView, TournamentDetailView,
                           TournamentAutocomplete, SeasonAutocomplete)
from teams.views import (import_teams,
                         PersonCreateView, PersonUpdateView,
                         TeamUpdateView, TeamSeasonView, TeamAllYearView,
                         TagAutocomplete, CityAutocomplete,
                         TeamAutocomplete, TeamSeasonAutocomplete,
                         PersonSeasonAutocomplete,
                         TeamBySeasonAutocomplete, PersonBySeasonAutocomplete)
from teams.viewsets import TeamViewSet, TeamSeasonViewSet, PersonViewSet, PersonSeasonViewSet
from matches.viewsets import MatchViewSet, SeasonViewSet
from users.viewsets import UserViewSet

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'teams', TeamViewSet)
router.register(r'teams-seasons', TeamSeasonViewSet)
router.register(r'persons', PersonViewSet)
router.register(r'personseasons', PersonSeasonViewSet)
router.register(r'teams/(?P<team_id>\d+)/documents', DocumentViewSet)
router.register(r'documents', DocumentViewSet)
router.register(r'sources', SourceViewSet)
router.register(r'issues', SourceObjectViewSet)
router.register(r'seasons', SeasonViewSet)
router.register(r'matches', MatchViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('allauth.urls')),
    url(r'^api/v1/', include(router.urls)),
    url(r'^api/v1/', include('authentication.urls')),
    #  url(r'^django-rq/', include('django_rq.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^import-teams/', import_teams),
    url(r'^import-seasons/', import_seasons, name='import_seasons'),
    url(r'^import-table/', import_table, name='import_table'),
    url(r'^dropbox-webhook/', import_from_dropbox),

    url(r'^autocomplete-tags/$', TagAutocomplete.as_view(),
        name='autocomplete-tags'),
    url(r'^autocomplete-cities/$', CityAutocomplete.as_view(),
        name='autocomplete-cities'),
    url(r'^autocomplete-tournaments/$', TournamentAutocomplete.as_view(),
        name='autocomplete-tournaments'),
    url(r'^autocomplete-seasons/$', SeasonAutocomplete.as_view(),
        name='autocomplete-seasons'),
    url(r'^autocomplete-teams/$', TeamAutocomplete.as_view(),
        name='autocomplete-teams'),
    url(r'^autocomplete-teamseasons/$', TeamSeasonAutocomplete.as_view(),
        name='autocomplete-teamseasons'),
    url(r'^autocomplete-personseasons/$', PersonSeasonAutocomplete.as_view(),
        name='autocomplete-personseasons'),
    url(r'^autocomplete-teambyseasons/$', TeamBySeasonAutocomplete.as_view(),
        name='autocomplete-teamseasons'),
    url(r'^autocomplete-personbyseasons/$', PersonBySeasonAutocomplete.as_view(),  # noqa
        name='autocomplete-personseasons'),

    url(r'^teams/$', views.teams_view, name='teams'),
    url(r'^teams/(?P<pk>\d+)/$',
        TeamUpdateView.as_view(), name='teams_detail'),
    url(r'^teams/(?P<pk>\d+)/(?P<year>\d{4})/all/',
        TeamAllYearView.as_view(), name='team_year_all'),
    url(r'^teams/(?P<team_pk>\d+)/(?P<year>\d{4})/(?P<pk>\d+)/',
        TeamSeasonView.as_view(), name='teamseason_detail'),
    url(r'^tournaments/$', TournamentListView.as_view(), name='tournaments'),
    url(r'^tournaments/(?P<pk>\d+)/$', TournamentDetailView.as_view(),
        name='tournament_detail'),
    url(r'^tournaments/(?P<tourn_pk>\d+)/(?P<lap>[\d\-]{4,7})/(?P<season_pk>\d+)/matches/(?P<pk>\d+)/',
        MatchDetailView.as_view(), name='match_detail'),
    url(r'^tournaments/(?P<tourn_pk>\d+)/(?P<lap>[\d\-]{4,7})/(?P<pk>\d+)/',
        SeasonDetailView.as_view(), name='season_detail'),
    url(r'^seasons/(?P<year>\d{4})/$', SeasonYearView.as_view(),
        name='seasons_year'),
    url(r'^seasons/new/$', SeasonCreateView.as_view(), name='seasons_new'),
    url(r'^persons/$', views.persons_view, name='persons'),
    url(r'^persons/(?P<pk>\d+)/', PersonUpdateView.as_view(),
        name='persons_detail'),
    url(r'^persons/new/', PersonCreateView.as_view(), name='persons_new'),

    url(r'^clippings/', views.clippings_view, name='clippings'),
    url(r'^contacts/', views.contacts_view, name='contacts'),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('tournaments'), permanent=False)),

    # the 'api-root' from django rest-frameworks default router
    # http://www.django-rest-framework.org/api-guide/routers/#defaultrouter
    url(r'^$', RedirectView.as_view(url=reverse_lazy('api-root'),
        permanent=False)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

rugbystat/teams/models.py
import datetime as dt

from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models, transaction
from django.db.models import Q
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _
from markdownx.models import MarkdownxField


class TagObject(models.Model):
    name = models.CharField(max_length=127, verbose_name=_('Базовое название'))
    story = MarkdownxField(verbose_name=_('История'), blank=True, )

    def __str__(self):
        return "Model: {0}".format(repr(self.target))

    @property
    def target(self):
        if getattr(self, 'team', None) is not None:
            return self.team
        if getattr(self, 'tournament', None) is not None:
            return self.tournament
        if getattr(self, 'season', None) is not None:
            return self.season
        if getattr(self, 'match', None) is not None:
            return self.match
        if getattr(self, 'person', None) is not None:
            return self.person
        return None

    @cached_property
    def documents(self):
        """
        >>> person.tagobject_ptr.document_set.all()
        <QuerySet [<Document: 1933>]>

        :return:
        :rtype:
        """
        return self.tagobject_ptr.document_set.all()


class City(models.Model):
    name = models.CharField(max_length=127, verbose_name=_('Базовое название'))
    short_name = models.CharField(
        max_length=4, verbose_name=_('Короткое название'), blank=True)

    class Meta:
        ordering = ('name', )

    def __str__(self):
        return self.name

    def get_short_name(self):
        return self.short_name or self.name


class Stadium(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name=_('Город'))
    name = models.CharField(max_length=127, verbose_name=_('Базовое название'))
    # TODO add historic names

    def __str__(self):
        return self.name


class Team(TagObject):
    CLUB = 'club'
    YOUTH = 'youth'
    NATION = 'nation'
    FOREIGN = 'foreign'
    TYPES = (
        (CLUB, CLUB),
        (YOUTH, YOUTH),
        (NATION, NATION),
        (FOREIGN, FOREIGN),
    )
    team_type = models.CharField(
        max_length=32, verbose_name=_('Короткое название'), choices=TYPES, default=CLUB,
    )
    short_name = models.CharField(
        max_length=32, verbose_name=_('Короткое название'), blank=True)
    city = models.ForeignKey(
        City, on_delete=models.CASCADE, verbose_name=_('Город'), related_name='teams')
    year = models.PositiveSmallIntegerField(
        verbose_name=_('Год создания'), blank=True, null=True,
        validators=(MinValueValidator(1900), MaxValueValidator(2100)),
    )
    disband_year = models.PositiveSmallIntegerField(
        verbose_name=_('Год распада'), blank=True, null=True,
        validators=(MinValueValidator(1900), MaxValueValidator(2100)),
    )
    year_prefix = models.CharField(
        max_length=64, verbose_name=_('Префикс к году образования'),
        blank=True, null=True,)
    disband_year_prefix = models.CharField(
        max_length=64, verbose_name=_('Префикс к году распада'),
        blank=True, null=True,)
    parent = models.ForeignKey(
        'self', on_delete=models.SET_NULL, verbose_name=_('Команда-родитель'),
        related_name='ancestors', blank=True, null=True)

    class Meta:
        ordering = ('year', )

    def __str__(self):
        team = self.short_name or self.name
        return "{} ({})".format(team, self.operational_years)

    def save(self, **kwargs):
        if not self.short_name:
            self.short_name = "{} {}".format(self.name,
                                             self.city.get_short_name())
        super(Team, self).save(**kwargs)

    @cached_property
    def operational_years(self):
        years = "{}{}".format(self.year_prefix or '',
                              self.year or '')
        if self.disband_year or self.disband_year_prefix:
            years += "-{}{}".format(self.disband_year_prefix or '',
                                    self.disband_year or '')
        return years

    def get_absolute_url(self):
        return reverse('teams_detail', kwargs={'pk': self.pk})

    def get_name_for(self, year, month=1, day=1):
        """Return name which team born in a given year."""
        default = self.short_name
        from_db = self.names.reverse().filter(
            from_day__lte=dt.date(year, month, day),
        ).filter(
            Q(to_day__gte=dt.date(year, month, day)) | Q(to_day__isnull=True)
        ).values_list('name', flat=True).first()
        return from_db or default


class TeamName(models.Model):
    """Representation of a separate name a team beared."""

    name = models.CharField(verbose_name=_('Базовое название'), max_length=127)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, verbose_name=_('Команда'), related_name='names')
    from_day = models.DateField(verbose_name=_('Дата начала'))
    to_day = models.DateField(verbose_name=_('Дата окончания'), blank=True, null=True)
    is_known = models.BooleanField(verbose_name=_('Подтверждено'), default=True)

    class Meta:
        ordering = ('team', 'from_day', )

    def __str__(self):
        years = '...'
        if self.is_known:
            if not self.to_day:
                years = "с {:%Y}".format(self.from_day)
            else:
                years = "{:%Y}-{:%Y}".format(self.from_day, self.to_day)
        return "{} ({})".format(self.name, years)


class TableRowFields(models.Model):
    place = models.CharField(
        verbose_name=_('Место'), max_length=2, blank=True,
    )
    played = models.PositiveSmallIntegerField(
        verbose_name=_('И'), null=True, blank=True,
        validators=(MaxValueValidator(100),),
    )
    wins = models.PositiveSmallIntegerField(
        verbose_name=_('В'), null=True, blank=True,
        validators=(MaxValueValidator(100),),
    )
    draws = models.PositiveSmallIntegerField(
        verbose_name=_('Н'), null=True, blank=True,
        validators=(MaxValueValidator(100),),
    )
    losses = models.PositiveSmallIntegerField(
        verbose_name=_('П'), null=True, blank=True,
        validators=(MaxValueValidator(100),),
    )
    points = models.PositiveSmallIntegerField(
        verbose_name=_('О'), null=True, blank=True,
        validators=(MaxValueValidator(200),),
    )
    score = models.CharField(
        verbose_name=_('Р/О'), max_length=10, blank=True
    )
    order = models.PositiveSmallIntegerField(
        verbose_name=_('Сортировка'), null=True, blank=True,
        validators=(MaxValueValidator(40),),
    )

    class Meta:
        abstract = True


class GroupSeason(TableRowFields):
    """Representation of each group in a tournament played"""

    name = models.CharField(verbose_name=_('Название команды в группе'),
                            max_length=127, blank=True)
    year = models.PositiveSmallIntegerField(
        verbose_name=_('Год'), blank=True, null=True,
        validators=(MinValueValidator(1900), MaxValueValidator(2100)),
    )
    # both `name` and `year` serves only for simpler repr and sql query
    team = models.ForeignKey(
        Team, on_delete=models.CASCADE, verbose_name=_('Команда'), related_name='groups',
    )
    group = models.ForeignKey(
        'matches.Group', on_delete=models.CASCADE, verbose_name=_('Группа'),
        related_name='standings'
    )
    story = models.TextField(verbose_name=_('История'), blank=True, )

    class Meta:
        ordering = ('order', '-year', 'team',)
        unique_together = (('team', 'group'),)

    def __str__(self):
        return "{}: {}".format(self.group, self.name)

    def save(self, **kwargs):
        if not self.year:
            self.year = self.group.date_end.year
        if not self.name:
            self.name = self.team.get_name_for(self.year)
        super(GroupSeason, self).save(**kwargs)

    def get_absolute_url(self):
        if self.team_id:
            team_in_m2m = self.group.teams.filter(team_id=self.team_id).first()
            if team_in_m2m:
                return team_in_m2m.get_absolute_url()

    def build(self):
        played, unknown_score = 0, 0
        wins, drws, loss = 0, 0, 0
        score_for, score_aga = 0, 0
        for match in self.group.matches():
            if self.team_id in (match.home_id, match.away_id):
                played += 1
                if match.is_unknown_outcome:
                    continue

                if match.is_team_win(self.team_id):
                    wins += 1
                if match.is_team_loss(self.team_id):
                    loss += 1
                if match.is_draw:
                    drws += 1
                
                if match.is_unknown_score:
                    unknown_score += 1
                else:
                    for_, aga_ = match.team_score(self.team_id)
                    score_for += for_
                    score_aga += aga_

        if wins + drws + loss != played:
            raise ValueError(f"{wins} + {drws} + {loss} != {played}")

        self.played = played
        self.wins = wins
        self.draws = drws
        self.losses = loss

        if not unknown_score:
            self.score = f"{score_for}-{score_aga}"
        return self


class TeamSeason(TableRowFields):
    """Representation of each tournament a team played"""

    name = models.CharField(
        verbose_name=_('Название команды в турнире'), max_length=127, blank=True
    )
    display_name = models.CharField(
        verbose_name=_('Полное наименование сезона'), max_length=127, blank=True,
    )
    year = models.PositiveSmallIntegerField(
        verbose_name=_('Год'), blank=True, null=True,
        validators=(MinValueValidator(1900), MaxValueValidator(2100)),
    )
    # both `name` and `year` serves only for simpler repr and sql query

rugbystat/main/forms.py
from django import forms
from django.db.models import Count

from clippings.models import Document, Source


def get_years():
    docs_qs = Document.objects.not_deleted().values(
        'year').annotate(count=Count('year')).values_list(
        'year', 'count', ).order_by('year')
    return tuple(
        [('', '---')] +
        [(doc[0], "{} (всего {})".format(doc[0], doc[1]))
        for doc in docs_qs]
    )


def get_sources():
    return tuple(
        [('', '---')] +
        [(source.id, source)
        for source in Source.objects.exclude(scans__isnull=True)]
    )


class ClippingsForm(forms.Form):
    year = forms.DateField(
        widget=forms.Select(
            choices=get_years(),
            attrs={'class': 'form-control'},
        )
    )
    source = forms.ChoiceField(
        choices=get_sources(),
        widget=forms.Select(attrs={'class': 'form-control'},)
    )
    source_type = forms.ChoiceField(
        choices=tuple([('', '---')] + list(Source.TYPE_CHOICES)),
        widget=forms.Select(attrs={'class': 'form-control'},)
    )

rugbystat/templates/_documents.html
<table class="table table-striped table-hover" id="documents-table">
  <thead>
    <tr>
      <th>Заголовок</th>
      <th>Источник</th>
      <th>Описание</th>
      <th>Месяц/Год</th>
      <th>Ссылка</th>
    </tr>
  </thead>
  <tbody>
    
  {% for doc in queryset %}
  <tr class="document-row">
    <td> {{ doc.title }} </td>
    <td> {{ doc.source_title | default_if_none:"???" }} </td>
    <td>{{ doc.description | default_if_none:"" | linebreaksbr }}</td>
    <td>
      {% if doc.date %}{{doc.date}}
      {% elif doc.month %}{{doc.month}}/{{doc.year | default_if_none:""}}
      {% else %}{{doc.year | default_if_none:""}}
      {% endif %}
    </td>
    <td> {% if doc.is_image %}
      <a class="dropbox-link" 
         href="{{ doc.dropbox_path }}">
         <img src="{{ doc.dropbox_thumb }}"/>
      </a>
    {% else %}
      <a class="dropbox-link" 
         href="{{ doc.dropbox_path }}">
         Нет превью
      </a>
    {% endif %}
    </td>
  </tr>
  {% endfor %}

  </tbody>
</table>

rugbystat/templates/_modal.html
<div class="modal fade" id={{modal_id}}>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> </h4>
      </div>
      <div class="modal-body">
        Благодарим за добавление. В ближайшее время правки будут рассмотрены модератором!
      </div>
    </div>
  </div>
</div>

rugbystat/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Вся регбийная статистика{% endblock title %}</title>
  {% block stylesheets %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-social.css' %}">
  {% endblock stylesheets %}
  {% block js %}
<!--   <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>  
 -->
   <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>
   <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
   <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
   <script type="text/javascript">
        var csrf_token = "{{ csrf_token }}";
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrf_token);
                }
            }
        });

        function updateQueryStringParameter(uri, key, value) {
          var re = new RegExp("([?&])" + key + "=.*?(&|$)", "i");
          var separator = uri.indexOf('?') !== -1 ? "&" : "?";
          if (key === undefined || value === undefined){
            return uri
          }
          if (uri.match(re)) {
            return uri.replace(re, '$1' + key + "=" + value + '$2');
          }
          else {
            return uri + separator + key + "=" + value;
          }
        }

    </script>

  {% endblock js %}
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-navbar-collapse">
        <span class="sr-only">Навигация</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="#">Регбийный архив</a>
    </div>

{% load socialaccount %}
{% providers_media_js %}

    <div class="collapse navbar-collapse" id="menu-navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'tournaments' %}">Турниры (по 1968)</a> <span class="sr-only">(current)</span></li>
        <li><a href="{% url 'teams' %}">Команды</a></li>
        <li><a href="{% url 'persons' %}">Персоны</a></li>
        <li><a href="{% url 'clippings' %}">Документы</a></li>
        <li><a href="{% url 'contacts' %}">Контакты</a></li>
      </ul>
      {% if user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'account_logout' %}"> {{ user }} </a></li>
      </ul>
      {% else %}
      <ul class="nav navbar-nav navbar-right">
        <a href="{% provider_login_url "facebook" method="js_sdk" %}" 
           class="btn btn-block btn-social btn-facebook">
          <span class="fa fa-facebook"></span> Sign in with Facebook
        </a>
      </ul>
      {% endif %}

    </div>
  </div>
</nav>

<div class="content container-fluid">
{% block content %}
{% endblock content %}
</div>
</body>
</html>

rugbystat/templates/contacts.html
{% extends "base.html" %}

{% load staticfiles %}

{% block stylesheets %}
{{ block.super }}
{% endblock stylesheets %}

{% block js %}
{{ block.super }}
{% endblock js %}


{% block content %}

<div id="contacts">
  <div>
    Если вы уже нашли какую-то ошибку, немедленно сообщите мне об этом. Если у вас есть результаты матчей, протоколы, число зрителей, авторы попыток, очков  и т.п. - не сочтите за труд поделиться со всеми. Ведь, как оказалось, эта статистика интересна очень многим. И я надеюсь, что все больше и больше любителей регби будет обращаться к этим данным, а мы - в свою очередь - будем стараться предоставлять их максимально точными.</div>
  <div>Я всегда доступен по адресам:</div>
  <div><a href="https://www.facebook.com/krnrrr">https://www.facebook.com/krnrrr</a></div>
  <div><a href="http://rugbystat.forum24.ru/">http://rugbystat.forum24.ru/</a></div>
  <div>
    Ну и огромное спасибо тем, без кого этот сайт не состоялся бы в принципе: Заалу Гигинешвили и aleko, Юрию Мазуру и Алексею Путееву, Дмитрию Воронину и Александру Ефанову, nicknov17, захару, RWC, Валерию Хроменкову и Олегу Баскакову, Роману Иванюхину и Сергею Чеченкову, Юрию Дайнеко и Тарасу Дацко, Дмитрию Горбачу и Владимиру Дашевскому и всем-всем-всем, кого забыл упомянуть. </div>
</div>

{% endblock content %}

rugbystat/templates/documents.html
{% extends "base.html" %}

{% load staticfiles %}

{% block css %}
{{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/modal.css' %}">
{% endblock css %}

{% block js %}
{{ block.super }}
  <script type="text/javascript" src="{% static 'js/documents.js' %}"></script>
  <script type="text/javascript">
    var documentListUrl = "{% url 'document-list' %}";
  </script>

{% endblock js %}


{% block content %}

  <form id="clippings-form" class="form-horizontal">
    <fieldset>
      <legend>Документы</legend>
  
      <div class="form-group col-lg-2" style="display:inline-block;">
        <label for="id_year" class="control-label">Год</label>
        {{ form.year }}
      </div>

      <div class="form-group col-lg-2" style="display:inline-block;">
        <label for="id_source" class="control-label">Источник</label>
        {{ form.source }}
      </div>

      <div class="form-group col-lg-2" style="display:inline-block;">
        <label for="id_source_type" class="control-label">Тип</label>
        <div class="input-group">
          {{ form.source_type }}
          <span class="input-group-btn">
            <button class="btn btn-primary" 
                    id="search-submit-btn" 
                    type="button">Искать</button>
          </span>
        </div>

      </div>
    </fieldset>
  </form>

<span id="indicator" style="display:none;">
  <img src="http://upload.wikimedia.org/wikipedia/commons/d/de/Ajax-loader.gif"/>
</span>

<div>
  <div>
    Всего в базе вырезок: 
    <ul>
      <li>фото: {{ total.photo }}</li>
      <li>из газет: {{ total.newspaper }}</li>
      <li>из журналов: {{ total.magazine }}</li>
      <li>протоколов: {{ total.protocol }}</li>
      <li>из программок: {{ total.program }}</li>
      <li>из книг: {{ total.book }}</li>
      <li>прочее: {{ total.other }}</li>
      <li>без указаний на источник: {{ null }}</li>
      <li>всего: {{ sum_total }}</li>
    </ul>
  </div>
</div>
<div id="results">
  <div class="documents-div">

    {% include '_documents.html' with queryset=qs.with_source_title %}

  </div>
</div>

{% include '_modal.html' %}

{% endblock content %}

rugbystat/templates/persons.html
{% extends "base.html" %}

{% load staticfiles %}

{% block stylesheets %}

{{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'css/modal.css' %}">
  <!-- Include Bootstrap Datepicker -->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" />
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css" />
{% endblock stylesheets %}

{% block js %}

{{ block.super }}
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/locales/bootstrap-datepicker.ru.js"></script>

  <script type="text/javascript" src="{% static 'js/persons.js' %}"></script>
  <script type="text/javascript">
    var personListUrl = "{% url 'person-list' %}";
  </script>

{% endblock js %}


{% block content %}

<div class="form-group">
  <label class="control-label" for="focusedInput">Персоны</label>

  <div class="letters">
    {% for liter in initial_letters %}
      <a href="#" class="letter">{{ liter }}</a>
    {% endfor %}
  </div>  
  
  <div class="input-group">
    <input type="text" class="form-control" id="person-input" />
    <span class="input-group-btn">
      <button class="btn btn-default" id="search-submit-btn" type="button">Искать</button>
    </span>
  </div>
</div>

<span id="indicator" style="display:none;"><img src="http://upload.wikimedia.org/wikipedia/commons/d/de/Ajax-loader.gif"/></span>
<div id="results"></div>

<div class="input-group">
  {% if request.user.is_superuser %}
  <button class="btn btn-default" id="showPersonForm" type="button">Добавить</button>
  {% endif %}
</div>

{% url 'persons_new' as action_url %}

{% include 'forms/edit_person.html' with action_url=action_url %}

{% include '_modal.html' %}

{% endblock content %}